### ISSUE TITLE
실행 이후 하드웨어 선택 목록이 playentry.org와 다르게 비어있습니다.

### ISSUE THREAD

**Issue by kjinwoo12** [entrylabs/entry-hw#161]
```
    $ sudo npm install
    npm WARN entry_hw@1.6.25 No repository field.
    npm WARN entry_hw@1.6.25 No license field.

    up to date in 1.841s

    $ npm start
```

위와 같이 entry-hw를 실행하였으나, playentry.org에서 다운로드 받은 연결 프로그램에서는 아두이노와 기타 제품들 목록이 보이며 선택할 수 있도록 되어있는데, 터미널에서 실행한 entry-hw 는 목록이 없었습니다. 정상적인 화면인가요?

**Comment by kimorkim** [comment]
@kjinwoo12 오류가 발생한것 같습니다.
다른 내용없이 보이지 않는다는 정보만 주셔서
어떤게 문제인지는 잘 모르겠습니다.

**Comment by kjinwoo12** [comment]
@kimorkim ubuntu 뭔지 모르겠는 상황이라 어떻게 도움을 받을 수 있을지조차 감이 안잡히네요.
그냥 실행해보려고 했던 것 뿐인데 이렇게 되어버리니 뭘 어떻게 말씀드려야 할지 모르겠습니다.

16.04 LTS 에서, npm 으로 실행한 entry-hw의 첫 화면이구요. 
![entry_ubu](https://user-images.githubusercontent.com/11540862/41632605-abe0c6ec-7475-11e8-8448-e49ef9264bb2.jpeg)
이건 win10에서, playentry.org에서 다운로드 받은 entry-hw의 첫 화면 입니다.
![entry_win](https://user-images.githubusercontent.com/11540862/41632656-ea2d3e3a-7475-11e8-9d54-15fc50a2c975.jpeg)

제가 한 행동은 다음 순서를 따랐습니다.
fork -> clone -> remote add upstream -> fetch upstream -> npm install -> npm start

아래는 clone 후 처음으로 npm install & start 를 했을 때 터미널 메시지를 복사한 것 입니다.
```
$ npm install

> electron@1.7.11 postinstall /home/....../git/entry-hw/node_modules/electron
> node install.js

npm WARN entry_hw@1.6.25 No repository field.
npm WARN entry_hw@1.6.25 No license field.

added 492 packages in 3.975s
$ npm start

> entry_hw@1.6.25 start /home/......./git/entry-hw
> set NODE_ENV=development&&electron -d app
```

무슨 이유에서인지 하드웨어 제품들 사진이 나와야 할 것으로 추측되는 <div id="hwList" class"content">가 비어있습니다.
계속 내용 추가하겠습니다.

**Comment by kimorkim** [comment]
@kjinwoo12 안녕하세요. 확인하신 platform 이 linux 이시네요.
entry-hw는 사용하는 platform에 따라서 지원하는 하드웨어 목록이 보입니다.
현재 하드웨어중에서 linux를 지원하는 하드웨어가 없어서 표기 되지 않습니다.
개발을 위해서 리스트를 보시기 위해서는

main.js에 addRobot function 에 있는 platform 로직을 지워주시면 됩니다.

소스 : https://github.com/entrylabs/entry-hw/blob/master/app/src/main.js#L299

**Comment by kjinwoo12** [comment]
감사합니다. 원활하게 해결되었습니다.
