### ISSUE TITLE
entry-hw 설치후에 하드웨어로 넘어가지 못하고 프로그램이 종료됩니다.

### ISSUE THREAD

**Issue by Taeyang-Choi** [entrylabs/entry-hw#221]
npm install 이후에 npm run start 명령어 실행하면
프로그램이 정상적으로 실행이 되고 하드웨어를 선택해서 들어가면
프로그램이 강제종료가 됩니다.

이후에 npx electron-rebuild 명령어를 실행하면 Rebuild Failed 가 되고
이후에 다시 npm run start 명령어를 실행하면 javascript 오류가 발생되어
엔트리 하드웨어 프로그램이 실행이 안됩니다.

[entry-hw 최초 실행시 생기는 warning]

![image](https://user-images.githubusercontent.com/22763090/58848089-2d198200-86c0-11e9-9b25-4207ad11c6f2.png)

[하드웨어 클릭시 다음 오류가 발생후에 강제종료가 됨]

![image](https://user-images.githubusercontent.com/22763090/58848135-618d3e00-86c0-11e9-83b5-16587ac6afbc.png)

[npx electron-rebuild 명령어 실행시 build failed 원문]

------------------------------------------------------------------

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\CHOILE\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\CHOILE\\Desktop\\Choile\\entry\\entry-hw\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.0.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\@entrylabs\bindings
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\CHOILE\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\CHOILE\\Desktop\\Choile\\entry\\entry-hw\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.0.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--msvs_version=2015"
gyp ERR! cwd C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\@entrylabs\bindings
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.next (C:\Users\CHOILE\Desktop\Choile\entry\entry-hw\node_modules\rxjs\internal\Subscriber.js:145:22)

------------------------------------------------------------------

[rebuild failed 이후에 npm run start 명령어 실행시 생기는 js 오류스크립트]

![image](https://user-images.githubusercontent.com/22763090/58848232-c052b780-86c0-11e9-81d7-ad003e88d4c5.png)

해당 오류에 대해서 답변을 요청합니다.
감사합니다.

**Comment by extracold1209** [comment]
@Taeyang-Choi 

> C:\Users\CHOILE\AppData\Local\Programs\Python\Python37\python.EXE 

node native addon 을 만드는 node-gyp 은 python 2.x 버전이 강제됩니다.
로그를 보면 기존에 python 3.7 이 환경변수 PATH 로 잡혀있어서 node-gyp 이 정상적으로 시리얼포트 라이브러리를 빌드하지 못했고,

결과적으로 하드웨어 시리얼포트 통신에서 에러가 발생하는 것으로 보입니다.
python 2.x 번대 설치 후 PATH 를 해당 위치로 수정해주신 후 빌드 재시도 해주시기 바랍니다.

**Comment by Taeyang-Choi** [comment]
@extracold1209 

python2.7.16 버전으로 설치후 electron-rebuild 실행하니 정상적으로 실행이 되었습니다.
감사합니다.
