### ISSUE TITLE
하드웨어를 빌드하고 싶은데 에러가 계속 나오네요..

### ISSUE THREAD

**Issue by rozen9938** [entrylabs/entry-hw#262]
하드웨어를 빌드하고 싶은데 에러가 계속 나오네요..
![스크린샷 2019-11-13 오후 2 17 44](https://user-images.githubusercontent.com/57659507/68735284-8814b500-0620-11ea-9b96-4e60ddf150f8.png)

![스크린샷 2019-11-13 오후 2 14 02](https://user-images.githubusercontent.com/57659507/68735156-1d637980-0620-11ea-8fce-5cc77131307f.png)

**Comment by extracold1209** [comment]
@rozen9938 안녕하세요.

해당 에러만 보고서는 문제를 알기 힘듭니다.
문제는 현재 개발환경에 따라 다를 수도 있는데요.

- 어떤 브랜치인가
- 브랜치는 최신과 동일한가
- https://github.com/serialport/electron-serialport 이 리포지토리를 실행시켰을때는 정상 빌드 되는가
  (빌드환경 확인. 시리얼포트 라이브러리에서 정식제공하는 리포지토리입니다)
