### ISSUE TITLE
엔트리 하드웨어 1.9.5에서 바이로봇 하드웨어 연결 시도를 하지 않습니다.

### ISSUE THREAD

**Issue by realwolf** [entrylabs/entry-hw#312]
엔트리 하드웨어 v1.9.5 프로그램을 받아서 테스트 해보니 '바이로봇 드론파이터 드론', '바이로봇 드론파이터 자동차', '바이로봇 드론파이터 조종기' 만 정상적으로 하드웨어 연결 시도를 하는 상태입니다.

이외의 다른 바이로봇 제품들은 연결 화면 상단에 '하드웨어와 연결을 시도하고 있습니다'라는 메세지가 나오지 않고 연결도 안되고 있습니다.

'바이로봇 페트론 V2 조종기' 같은 경우는 json 파일의 vendor 배열 순서를 변경한 것 밖에 없는데, 기존 버전에서 정상적으로 연결되던 것이 현 버전에서는 연결되지 않습니다.

이외의 제품들은 PR 전 테스트하는 상황에서는 정상적으로 연결되었던 것들입니다.

혹시 제가 작업한 부분 이외의 다른 부분에서 수정이 필요한 것인지 알려주시면 좋겠습니다.

**Comment by realwolf** [comment]
혹시나 해서 'C:\Entry_HW\resources\modules' 경로의 json 파일에 있는

    "module": "byrobot_petrone_v2_controller.js", 를
    "module": "byrobot_dronefighter_controller.js", 로 변경해보니

정상적으로 장치 연결을 시도하는 것을 확인하였습니다.

두 프로젝트의 차이는 정상 동작하는 것은 function Module()로 시작하고,
연결이 안되는 프로젝트는 class 로 정의한 것입니다.

둘 다 'npm run start'로 실행했을 때에는 정상 작동합니다.

**Comment by extracold1209** [comment]
현재 재택근무로 인해 디바이스 테스트가 어려운 상황이므로, 최대한 빠른 시일 내 확인해보겠습니다.

**Comment by extracold1209** [comment]
@realwolf 

먼저, 이번에 추가하신 하드웨어들 및 의 경우 샘플 미보유로 정상적인 테스트가 어렵습니다.
맥에서 테스트해본 결과로는,

드론파이터 드론 연결 후 E-Drone 연결시 정상연결 확인하였습니다.
이때 handShake 시 보낸 버퍼는 [10, 85, 1, 8, 130, 16, 0, 0, 0, 0, 0, 0, 0, 0, 187, 200] 입니다.

드론파이터 드론 연결 후 드론파이터 연결 시 연결은 불가하나, 시리얼포트는 정상접속 확인되었습니다.
이때 handShake 를 위해 보낸 버퍼는 [10, 85, 1, 4, 21, 17, 0, 0, 0, 0, 155, 113] 입니다.
이 버퍼를 송신하였으나 드론파이터 측에서는 어떠한 response 도 보내주고 있지 않습니다. 그래서 연결이 성사되지 않고 있습니다.

상황이 뭔가 반대되고 있는 것 같은데, 시리얼포트 연결까지는 정상적으로 이루어 지고 있는 것으로 보아, 버퍼의 송수신간 문제가 있지 않나 생각됩니다.

자세하게 설명 부탁드립니다

**Comment by extracold1209** [comment]
@realwolf 문제점으로 보이는 부분 (문제가 있는 디바이스가 연결중입니다라는 토스트조차 뜨지 않고 연결이 되지 않는 문제) 가 확인되어 조치중입니다.

해당 문제는 코어 전역에서 발생하고 있으므로 문제가 수정되는대로 핫픽스 조치 할 예정입니다.

**Comment by realwolf** [comment]
@extracold1209

E-Drone 조종기를 디버깅 모드로 PC에 연결해놓고, 엔트리 하드웨어에서 '바이로봇 E-DRONE 조종기'에 연결하는 테스트를 해보았습니다.

1. 'npm run start'로 엔트리 하드웨어 프로그램을 실행하여 E-Drone 조종기에 연결하는 경우엔 디버깅 중인 하드웨어에서 USB가 연결된 상태로 바뀌고, 정상적으로 데이터를 송수신합니다. 이 때 노란색 바탕위에 '하드웨어와 연결되었습니다.'라는 메세지를 출력합니다. 
'https://playentry.org/ws#!/' 에 들어가면 정상적으로 하드웨어 블럭들이 표시되고 작동합니다.

2. v1.9.5 버전의 엔트리 하드웨어 프로그램을 실행하여 E-Drone  조종기와 연결하면 디버깅 중인 하드웨어에서 상태가 바뀌지 않습니다. 데이터도 수신받지 못합니다. PC에 연결된 시리얼 통신 장치가 하나뿐인 경우에도 연결하지 않는 것으로 보입니다.

3. E-DRONE, E-DRONE 조종기, 코딩 드론은 Baudrate가 모두 57600인데 현재 115200으로 설정되어 있습니다. 하지만 다른 프로그램에서 Baudrate를 57600으로 하던 115200으로 하던 정상적으로 연결되는 것으로 보아 이 문제는 아닐 것 같습니다.

**Comment by teamong** [comment]
저희 HW(mechatro) 도 연결 시도를 하지 않습니다.
 "연결 시도중입니다" 안내가 나오지 않습니다.
핫픽스때 같이 확인 부탁드립니다.

**Comment by extracold1209** [comment]
@teamong @realwolf 

엔트리 하드웨어 버전업 없이 파일이 교체되었습니다. 다시 다운로드 후 확인해주세요

**Comment by realwolf** [comment]
@extracold1209 정상 연결되는 것을 확인하였습니다. 감사합니다.

**Comment by teamong** [comment]
감사합니다. 온라인 버전은 연결이 잘 됩니다.
오프라인 버전(2.0.19)도 동일한 문제 있습니다.
이건 아직 업데이트가 안된 것 같은데
오프라인 버전도 확인 부탁드립니다.
