### ISSUE TITLE
[Question]Console

### ISSUE THREAD

**Issue by TaeJuneJoung** [entrylabs/entry-hw#362]
Console로 데이터 통신에 대해서 어떻게 이뤄지는지 디버깅을 하려고 하는데
터미널에 찍히지가 않아 문의드립니다.

hw에 js파일에 console.log(handler) 이런식으로 하면은
JS -> HW에 통신을 확인할 수 없을까요?

**Comment by extracold1209** [comment]
@TaeJuneJoung 브라우저에서 온 데이터를 확인하기 위해서는 하드웨어 모듈파일의 handleRemoteData 쪽을 확인하시면 됩니다.

브라우저 워크스페이스가 실행중일때만 데이터를 전송하므로 이점 유의해주시기 바랍니다.  
(단순히 연결만 성립된 상태에서는 실제 데이터를 주고받지 않습니다)

**Comment by TaeJuneJoung** [comment]
EntryJS 구동 상태에서 Entry-HW을 진행하고 있습니다.
handleRemoteData 시작하는 첫 라인에서 console.log를 사용하였고,
EntryJS에서 구동한 웹에서 연결한 후에, 블럭을 넣고 실행을 하였는데도 터미널에 console내용이 찍히지 않습니다.

**Comment by TaeJuneJoung** [comment]
Teminal의 문제였습니다. 감사합니다!
