### ISSUE TITLE
수정된 언어를 수시로 디버깅 방법 안내부탁드립니다.

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-hw#424]
안녕하세요?

en.js 상에 내용을 일부 수정한 후, 확인을 위하여 
ReadMe에 나와있는데로 yarn run start -l:en 이런식으로 실행을 시킨다음에 어떻게 확인해야 하는 것인지요?
별로로 공식 릴리즈된 Entry 프로그램과 연동되어 변경한 언어 수정사항이 보여지는 것으로 기대했는데, 전혀 변화가 없는데요???
어떻게 변경사항을 수시로 확인하며 디버깅이 가능한지 안내부탁드립니다. 
https://entrylabs.github.io/docs/guide/entry-hw/2016-05-01-getting_started.html 문서에도 방법이 안내되어 있지 않네요.

감사합니다.

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 
웹팩 번들링을 동시에 진행 하셔야 할것 같은데요.
yarn webpack:watch를 진행하시면서 다른 터미널 창에서 yarn debug로 진행하시면 될 것 같습니다.
