### ISSUE TITLE
[Feature Request] 하드웨어 블록으로 코딩한 내용을 하드웨어에 다운로드 하기 기능

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-hw#436]
엔트리가 아두이노를 포함해 많은 특히 국산 수많은 하드웨어의 블럭코딩을 지원하는 유일한 대안입니다. 그래서, 국산 코딩용 하드웨어 해외진출에 있어서도 엔트리의 동반진출이 반드시 필요한 경우가 많구요.

그런데, 엔트리의 가장 경쟁업체라고 할 수 있는 mBlock(최근 5.x버전은 환골탈퇴해서 파이썬도 지원 시작)에 비해 가장 부족한 기능이 블록코딩한 내용을 하드웨어로 다운로드 할 수 없다는 것입니다.  디버깅하는 동안은 상관없으나, 최종 잘 정제된 코드를  하드웨어를 다운로드해, 이후는 엔트리 분리 후에도 계속 하드웨어 스스로가 다운로드 된 코드기반에 동작할 수 있게 해야 합니다. 이게 MCU의 목적 자체에도 가장 부합하고요. 

잘 아시다시피 매번 하드웨어를 실행시키기 위해 엔트리를 하드웨어에 연결하고, 컴퓨터에 저장된 코드를 로딩하고 하는게 상당히 번거롭습니다.
그럼, 심각하게(?) 고려를 부탁드립니다.

전부다 어렵더라도 아두이노나 마이크로빗 같은 오픈소스 방식 하드웨어만이라도 꼭좀 지원하면 좋을 것 같습니다. 

감사합니다.

**Comment by wodnjs6512** [comment]
@JeongJun-Lee 
문의 주신 부분은 엔트리만으로 펌웨어를 제작하여 하드웨어에 플래싱을 하는 방식을 말씀하시는것 같은데요. 
엔트리에서 현재 제공하는 형태와 맞지 않는 방식으로 보이며, 해당 방향을 추가할 계획이 없습니다.

예시로 마이크로비트는 엔트리에 맞는 펌웨어를 엔트리 팀에서 개발하여서 제공하고 있으며, 해당 펌웨어를 통해서 엔트리와 통신하여 동작할수 있도록 제작 되어있습니다.

**Comment by JeongJun-Lee** [comment]
@wodnjs6512 구현계획이 없으시다 하여 제가 아쉬워 직접 구현했습니다. 필요하신 분 이용부탁 드립니다. https://github.com/JeongJun-Lee/entry-offline
