### ISSUE TITLE
안녕하세요. 프로보 소프트웨어 개발팀입니다.

### ISSUE THREAD

**Issue by zptmxj** [entrylabs/entry-hw#492]
최근 업데이트 이후 프로보커넥트를 하드웨어 연결하면 하드웨어블럭이 나타나지 않는 문제가 확인되었습니다.

오프라인버전에서는 하드웨어 블럭이 나타나지만 웹버전에서 나타나지 않는 문제가 확인 됩니다.

저희 쪽에서 수정이 필요한 부분인지 문의 드립니다.

**Comment by Tnks2U** [comment]
@zptmxj 
안녕하세요. 
늦게 답변해드려 죄송합니다.
혹시 현재도 문제가 해결되지 않으셨나요?

만약 문제가 해결되지 않았다면, 좀 더 상세한 재현상황(하드웨어 프로그램 버전, 하드웨어 프로그램과 하드웨어 연결 여부, WS의 화면캡쳐 등)을 알려주시면 대처하도록 하겠습니다.

좀 더 빠른 답변을 원하신다면, 엔트리 고객센터(entry@connect.or.kr)로 연락주시면 보다 빠른 대처가 가능합니다.
감사합니다.
