### ISSUE TITLE
커스텀 하드웨어 ble 지원 여부 질문

### ISSUE THREAD

**Issue by HwangGB** [entrylabs/entry-hw#747]
안녕하세요, 커스텀 하드웨어를 엔트리와 연결하기 위해 작업 중인 개발자입니다.
https://docs.playentry.org/guide/entry-hw/add_bluetooth_hardware.html#%EB%AA%A8%EB%93%88%EC%97%90-%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A4-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
위 위키 페이지를 참고하여 프로그램을 작성 중에, ble 관련 업데이트가 있는지 여쭤보고자 글 남깁니다.
현재 마이크로비트와 실과 로봇의 경우 ble를 이용할 수 있는 듯 한데, 타 로봇의 경우에도 ble를 활용할 수 있는 방법이 있을까요? + 본 github에 있는 ble 코드를 사용하기 위해 추가로 해야 하는 작업이 있나요? (ex - 로봇 드라이버 hex파일 등)

답변 기다리겠습니다.
감사합니다.

**Comment by Tnks2U** [comment]
@HwangGB 
안녕하세요. 답변이 늦어서 죄송합니다.
추후 질문이 있으시면, 엔트리 하드에어 채널(dl_entry_hw@nts-corp.com)로 연락주시면 더 빠른 답변을 받으실 수 있습니다.

우선, 현재 엔트리 하드웨어는 공식적으로 ble 연결을 지원하고 있지는 않습니다.
크로미움의 web bluetooth api를 사용하여 ble연결을 시도하였으나, 블루투스 동글을 사용해서 win10환경에서 연결시 불안정하다는 문제가 있어 2020년 경 개발이 중지되었습니다.(상세한 이유는 당시 담당자분이 퇴사하셔서 확인이 어렵습니다.)
게다가, 기기별로 사용하는 bluetooth service가 다르기에 현재 엔트리hw의 구조에서 어떻게 외부 제조사들이 서비스를 등록하고 사용할지에 대한 문제도 있었습니다.

현재는, entryjs에서 지원하는 '브라우저로 연결하기' 기능으로 마이크로비트 한정 web ble기능을 제공하는 중입니다.(https://github.com/entrylabs/entryjs/blob/develop/src/class/hardware/webBluetoothConnector.ts)

만약, 현재 entry-hw에서 ble를 사용하고 싶으시다면 아래의 작업이 필요합니다.
1. 추가할 하드웨어 모듈의 json파일에 type을 'ble'로 세팅합니다.
2. 필요시 [BleScanner](https://github.com/entrylabs/entry-hw/blob/1cbdb5c2a8202657ae5c29a1b0d244d17c52dc74/app/src/main/core/ble/scanner.ts#L12)에서 해당 모듈을 스캔할수 있게 수정합니다.
3. [BleProcessManager](https://github.com/entrylabs/entry-hw/blob/1cbdb5c2a8202657ae5c29a1b0d244d17c52dc74/app/src/preload/bleProcessManager.ts#L4)에서 연결된 기기와 통신할 수 있게 수정이 필요합니다. 현재는 연결된 기기의 gatt에서 모든 service를 불러와 등록후 통신합니다. 자세한 통신방법은 해당 클래스의 내부 함수들을 참고 부탁드립니다.
4. 위 클래스의 생성위치는 [preload](https://github.com/entrylabs/entry-hw/blob/1cbdb5c2a8202657ae5c29a1b0d244d17c52dc74/app/src/preload/index.ts#L16)입니다. 필요에 따라서 수정하시면 됩니다.

크로미움의 web bluetooth api를 사용하기에 nodejs에서 동작하던 기존 하드웨어들과 다르게 renderer에서 모든 로직을 처리해야 합니다.
따라서, 기존의 하드웨어의 라이프사이클을 사용할 수 없으므로, 이부분은 직접 개발이 필요합니다.

도움이 되셨길 바랍니다.
