### ISSUE TITLE
하드웨어 전용 블럭들을 다른 언어로 번역하는 하는 방법을 알려주세요

### ISSUE THREAD

**Issue by JeongJun-Lee** [entrylabs/entry-hw#89]
안녕하세요? 개도국에서 봉사단원으로 활동 중에 있습니다.

개도국에서 엔트리와 엔트리에 하드웨어(예를 들어 햄스터)를 연결해 수업을 진행해 보고 싶은데, 현지어로 번역이 필요합니다. 번역하는 방법을 알려주실 수 있는지요? 이달 마지막 주에 수업 하려는데 번역 후 공식 버전 반영까지 시간이 많이 걸린다면  제가 직접 빌드한 커스텀 버전을 사용할 수도 있는지요?

감사합니다.

**Comment by kimorkim** [comment]
안녕하세요. 엔트리교육연구소 김정용 연구원입니다.
번역관련해서 질문을 주셨는데요. 현재 실제로 운영되고 있는 번역 부분은 따로 공유해서 개발하고 있지는 않습니다.
다만, 하드웨어 블록개발시 확인 및 추가 번역을 위해서 [entryjs](https://github.com/entrylabs/entryjs) 
레포지토리에 있는 extern/lang 폴더내에 있는 다국어 파일을 통해 
기본적으로 다국어 번역을 진행하고 있습니다.

다만 지원하려 하시는 현지어가 어떻게 되는지는 잘모르겠으나 단순히 블록을만 번역이 필요한것이 아니고 사이트 전반적으로 번역이 필요한 경우가 있을수 있어 단순이 다국어 파일 1개 추가 이외의 다른 작업들이 발생 할 여지가 있어 보입니다.

**Comment by JeongJun-Lee** [comment]
네 전반적인 다른 부분도 다 번역이 필요할텐데요. 우선 급한데로 우선순위별로 나누어 진행하려고 합니다. 
하드웨어 용도 블럭도 entryjs/extern/lang 에서 번역을 해 놓으면 된다는 말씀이지요? 여기는 전기와 네트워크 사정으로 오프라인 버전을 사용해야 합니다. 만약 거기에 번역을 해서 추가해놓으면 언제쯤 그 언어가 반영된 오프라인 에디터 버전이 릴리즈 될 수 있을까요? 시간이 별로 없어서 아니면 제가 개인적으로 해당 언어를 적용한 커스텀 버전을 빌드해 사용할 수 있다면 빌드하는 방법을 안내받을 수 있을까요?

감사합니다.

**Comment by kimorkim** [comment]
일단 entryjs/extern/lang을 수정하셔서 테스트를 진행 하실수는 있고 
[offline](https://github.com/entrylabs/entry-offline/tree/master/app/lang)의 경우 비슷한 파일을
app/lang 밑에 넣어서 처리하고 있습니다.
해당 파일을 수정또는 추가 하시고 오프라인의 language 부분을 수정하시면 해당 언어로 표현이 가능해 집니다.
다만 현재로선 오프라인 관련 개발 가이드는 따로 작성되지 않은 상태이기에 오프라인 관려 소스 분석은
따로 하셔야 할것으로 보입니다.

**Comment by JeongJun-Lee** [comment]
사실은 이 교육을 워낙 다국어 지원이 잘되어있는 MIT의 스크래치와 mBot이라는 중국업체 제품으로 진행하려고 최근 번역도 다 마친 상태입니다만, 가능하면 우수한 한국 기술(관련 하드웨어 포함) 을 현지에 소개하고, 이 교육은 일회성 이벤트성 목적이 아니고 현지 대학에서 관련 인력 양성이 이뤄지고 배출된 인력이 초중고에 가서 가르치는 장기적 관점에서 진행하고 있습니다. 따라서 장기적으로는 추가적인 하드웨어 구매로도 이뤄질 수 있는 여지도 있어 가능하면 한국 기업이 현지에 제품 수출도 할 수 있는 기반을 마련하는 것이 좋겠다는 판단이 들어, 엔트리와 관련 하드웨어(예를 들어 햄스터)를 가지고 해보는게 어떨까 해서 이렇게 연락을 드리고 있는 중입니다. 이곳은 인터넷과 전기가 안좋으니 오프라인 에디터를 쓸 수 밖에 없고 필요한 번역과 커스텀 버전은 제 스스로 만들어 사용해 볼까 합니다. 소스 분석은 제가 개인적인 시간을 내서 해 볼 수 있습니다만, 수업 시작까지 시간이 넉넉지 않아서 아마 업무로 바쁘시겠지만, 오픈 소스 확산을 위해서라도, 해당 오프라인 버전용 커스텀 버전 빌드하는 방법에 대한 기본적인 안내는 해주시면 큰 도움이 될 것 같습니다. 감사합니다.

**Comment by kimorkim** [comment]
음. 저희쪽에서 해당 가이드를 작성하는데 시간이 현재 필요한 상태입니다.
혹시 해당 교육이 언제 부터 시작하시는지요?
대략적인 일정이 확보되어야 하는상황이기때문에 일정을 보고나서 말씀드릴수 있을것 같습니다.

**Comment by JeongJun-Lee** [comment]
교육 시작은 2/20일 부터 시작하게 될 것입니다. 그전까지는 언급해주신데로 app/lang 안에 en.js 파일을 수정해서 번역과 번역테스트를 해보겠습니다. 이 오프라인 버전이 포터블 버전이 있다면 따로 커스텀 빌드없이 언어파일만 바꿔져서 배포가 가능하다면 그렇게라도 해볼텐데 포터블 버전은 없지 않나요? 참고로 저희가 필요한 버전 플랫폼은 윈도우즈용입니다. 감사합니다.

**Comment by kimorkim** [comment]
현재 오프라인 버전이 단순한편이어서 설치된 상태그대로 복사해서 사용하실수 있습니다.
레지스트리에 정보가 들어가지 않아서 일부 기능이 동작하지 않으나 일반적인 동작은 잘 작동합니다.

**Comment by JeongJun-Lee** [comment]
언급해주신 일반적인 동작이 잘 동작한다고 해주신 부분은 햄스터 같은 하드웨어 제어까지도 포함된 것인지요?

**Comment by kimorkim** [comment]
네 레지스트리에 포함되는 내용은 설치 위치표시나 자동실행 ent파일로 실행하기등 대체로 불러 오기 또는 실행과 관련 있습니다.
일단 실행된 이후에는 모든 기능이 동작할것으로 예상 됩니다.

**Comment by JeongJun-Lee** [comment]
결국 두 프로그램, 엔트리 에디터도 그대로 복사해 사용할 수 있고, 별도로 하드웨어 연결용으로 제공하시는 프로그램도 그대로 설치없이 복사해 써도 문제가 없단 말씀이지요? 네 그럼 한번 그렇게 진행보겠습니다^^ 만약 해보다가 발생하는 문제가 있으면 다시 이슈를 남기겠습니다. 감사합니다.

**Comment by kimorkim** [comment]
예 그러면 해당 이슈는 닫도록 하겠습니다.
